spring:
  redis:
    host: 39.108.225.237
    port: 6379
    password: rds
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.225.237:3306/cloud_backend?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      auto-commit: true
      idle-timeout: 30000
      pool-name: AUTHCENTER-HIKAIRCP
      connection-timeout: 50000

server:
  port: 0
  servlet:
    context-path: /backend

security:
  oauth2:
    resource:
      user-info-uri: http://39.108.225.237:9001/process/auth/api/sec/principal
      prefer-token-info: false