spring:
  redis:
    host: dl.love.com
    port: 6379
    password: rds
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
server:
  port: 9001

zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    auth:
      path: /auth/**
      serviceId: auth-center
    backend: 
      path: /backend/api/**
      url: http://192.168.2.72:9999

feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: FULL # NONE: 不记录信息, BASIC:仅记录请求方法，URL以及
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  # hystrix:
  #   enabled: true  
  
ps:
  security:
    cors:  
      allowCredentials: true
      allowedOrigins: "*"
      allowedHeader: "*"
      allowedMethods: "*"
      maxAge: 1800
      allow: "*"
      path: "/**"
    csrf: 
      enable: false
    oauth2:
      clientId: ps_zuul_center
      clientSecret: password
      defaultSecret: false